# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 17:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 23, 17, 13, 38, 873993))),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
