# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 15:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20170723_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='todos',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 25, 15, 35, 4, 372694)),
        ),
    ]
