# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 15:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20170725_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name_plural': 'Priorities'},
        ),
        migrations.AddField(
            model_name='todos',
            name='priority',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todos.Priority'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todos',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 25, 15, 47, 33, 746141)),
        ),
    ]
